<?php
return array (
  'app' => 'Admin',
  'model' => 'Advantage',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => ' 纳网的优势',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Portal',
      'model' => 'AdminCutForm',
      'action' => 'edit',
      'data' => 'id=6',
      'type' => '1',
      'status' => '1',
      'name' => '资深专业',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminCutForm',
      'action' => 'edit',
      'data' => 'id=7',
      'type' => '1',
      'status' => '1',
      'name' => '即使响应',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminCutForm',
      'action' => 'edit',
      'data' => 'id=8',
      'type' => '1',
      'status' => '1',
      'name' => '安全绝密',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminCutForm',
      'action' => 'edit',
      'data' => 'id=9',
      'type' => '1',
      'status' => '1',
      'name' => '覆盖全球',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);