<?php
return array (
  'app' => 'Portal',
  'model' => 'AdminCutForm',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '成为代理',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Portal',
      'model' => 'AdminCutForm',
      'action' => 'edit',
      'data' => 'id=10',
      'type' => '1',
      'status' => '1',
      'name' => '合作优势',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminCutForm',
      'action' => 'edit',
      'data' => 'id=11',
      'type' => '1',
      'status' => '1',
      'name' => '服务优势',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminCutForm',
      'action' => 'edit',
      'data' => 'id=12',
      'type' => '1',
      'status' => '1',
      'name' => '合作流程',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);